name: NuGet Publish

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MainProject: Obfuscation.Fody
      NuGetProject: Obfuscation.Fody.NuGet
      Configuration: Release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore $MainProject project dependencies
      run: dotnet restore src/$MainProject/$MainProject.csproj
    - name: Build $MainProject project
      run: dotnet build src/$MainProject/$MainProject.csproj --no-restore --configuration $Configuration
    - name: Pack and publish package to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/$NuGetProject/$NuGetProject.csproj
        PACKAGE_NAME: $MainProject
        VERSION_FILE_PATH: Directory.Build.props
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: publish package to GitHub
      run: dotnet nuget push *.nupkg --api-key ${{secrets.PUBLISH_TO_GITHUB_TOKEN}} --source "github" --skip-duplicate
